import React from "react";
import TimeLineCard from "./TimeLineCard";
import moon from "../moon.gif";
import sun from "../sun.gif";

function Forecast() {
  let response = {
    location: {
      name: "Loni Kalbhor",
      region: "Maharashtra",
      country: "India",
      lat: 18.45,
      lon: 74.03,
      tz_id: "Asia/Kolkata",
      localtime_epoch: 1721934678,
      localtime: "2024-07-26 0:41",
    },
    current: {
      last_updated_epoch: 1721934000,
      last_updated: "2024-07-26 00:30",
      temp_c: 21.3,
      temp_f: 70.4,
      is_day: 0,
      condition: {
        text: "Partly Cloudy",
        icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
        code: 1003,
      },
      wind_mph: 8.5,
      wind_kph: 13.7,
      wind_degree: 246,
      wind_dir: "WSW",
      pressure_mb: 1003,
      pressure_in: 29.61,
      precip_mm: 0,
      precip_in: 0,
      humidity: 93,
      cloud: 61,
      feelslike_c: 21.3,
      feelslike_f: 70.4,
      windchill_c: 21.3,
      windchill_f: 70.4,
      heatindex_c: 24.2,
      heatindex_f: 75.6,
      dewpoint_c: 20.2,
      dewpoint_f: 68.3,
      vis_km: 10,
      vis_miles: 6,
      uv: 1,
      gust_mph: 12,
      gust_kph: 19.3,
    },
    forecast: {
      forecastday: [
        {
          date: "2024-07-26",
          date_epoch: 1721952000,
          day: {
            maxtemp_c: 24.8,
            maxtemp_f: 76.6,
            mintemp_c: 21.1,
            mintemp_f: 70,
            avgtemp_c: 22.9,
            avgtemp_f: 73.3,
            maxwind_mph: 17.2,
            maxwind_kph: 27.7,
            totalprecip_mm: 3.28,
            totalprecip_in: 0.13,
            totalsnow_cm: 0,
            avgvis_km: 9.3,
            avgvis_miles: 5,
            avghumidity: 89,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 89,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 9,
          },
          astro: {
            sunrise: "06:10 AM",
            sunset: "07:12 PM",
            moonrise: "11:04 PM",
            moonset: "10:53 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: 74,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1721932200,
              time: "2024-07-26 00:00",
              temp_c: 21.1,
              temp_f: 70,
              is_day: 0,
              condition: {
                text: "Cloudy ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 231,
              wind_dir: "SW",
              pressure_mb: 1003,
              pressure_in: 29.63,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 81,
              feelslike_c: 21.1,
              feelslike_f: 70,
              windchill_c: 21.1,
              windchill_f: 70,
              heatindex_c: 24.1,
              heatindex_f: 75.5,
              dewpoint_c: 20.1,
              dewpoint_f: 68.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.5,
              gust_kph: 18.5,
              uv: 0,
            },
            {
              time_epoch: 1721935800,
              time: "2024-07-26 01:00",
              temp_c: 21.3,
              temp_f: 70.4,
              is_day: 0,
              condition: {
                text: "Partly Cloudy ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                code: 1003,
              },
              wind_mph: 8.5,
              wind_kph: 13.7,
              wind_degree: 246,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.61,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 61,
              feelslike_c: 21.3,
              feelslike_f: 70.4,
              windchill_c: 21.3,
              windchill_f: 70.4,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 20.2,
              dewpoint_f: 68.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12,
              gust_kph: 19.3,
              uv: 0,
            },
            {
              time_epoch: 1721939400,
              time: "2024-07-26 02:00",
              temp_c: 21.3,
              temp_f: 70.3,
              is_day: 0,
              condition: {
                text: "Cloudy ",
                icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
                code: 1006,
              },
              wind_mph: 8.1,
              wind_kph: 13,
              wind_degree: 247,
              wind_dir: "WSW",
              pressure_mb: 1002,
              pressure_in: 29.6,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 75,
              feelslike_c: 21.3,
              feelslike_f: 70.3,
              windchill_c: 21.3,
              windchill_f: 70.3,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 19.9,
              dewpoint_f: 67.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.4,
              gust_kph: 18.4,
              uv: 0,
            },
            {
              time_epoch: 1721943000,
              time: "2024-07-26 03:00",
              temp_c: 21.3,
              temp_f: 70.3,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 7.4,
              wind_kph: 11.9,
              wind_degree: 240,
              wind_dir: "WSW",
              pressure_mb: 1002,
              pressure_in: 29.6,
              precip_mm: 0.23,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 21.3,
              feelslike_f: 70.3,
              windchill_c: 21.3,
              windchill_f: 70.3,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 20.1,
              dewpoint_f: 68.1,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 10.5,
              gust_kph: 16.9,
              uv: 0,
            },
            {
              time_epoch: 1721946600,
              time: "2024-07-26 04:00",
              temp_c: 21.3,
              temp_f: 70.4,
              is_day: 0,
              condition: {
                text: "Light rain",
                icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
                code: 1183,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 254,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.61,
              precip_mm: 1.16,
              precip_in: 0.05,
              snow_cm: 0,
              humidity: 95,
              cloud: 100,
              feelslike_c: 21.3,
              feelslike_f: 70.4,
              windchill_c: 21.3,
              windchill_f: 70.4,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 20.4,
              dewpoint_f: 68.7,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 9,
              vis_miles: 5,
              gust_mph: 10.6,
              gust_kph: 17.1,
              uv: 0,
            },
            {
              time_epoch: 1721950200,
              time: "2024-07-26 05:00",
              temp_c: 21.3,
              temp_f: 70.4,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 8.3,
              wind_kph: 13.3,
              wind_degree: 259,
              wind_dir: "W",
              pressure_mb: 1003,
              pressure_in: 29.61,
              precip_mm: 0.68,
              precip_in: 0.03,
              snow_cm: 0,
              humidity: 95,
              cloud: 100,
              feelslike_c: 21.3,
              feelslike_f: 70.4,
              windchill_c: 21.3,
              windchill_f: 70.4,
              heatindex_c: 24.2,
              heatindex_f: 75.6,
              dewpoint_c: 20.6,
              dewpoint_f: 69,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 11.7,
              gust_kph: 18.9,
              uv: 0,
            },
            {
              time_epoch: 1721953800,
              time: "2024-07-26 06:00",
              temp_c: 21.8,
              temp_f: 71.2,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.63,
              precip_mm: 0.16,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 93,
              cloud: 95,
              feelslike_c: 21.8,
              feelslike_f: 71.2,
              windchill_c: 21.8,
              windchill_f: 71.2,
              heatindex_c: 24.4,
              heatindex_f: 75.9,
              dewpoint_c: 20.6,
              dewpoint_f: 69.1,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.7,
              gust_kph: 25.2,
              uv: 5,
            },
            {
              time_epoch: 1721957400,
              time: "2024-07-26 07:00",
              temp_c: 22.2,
              temp_f: 71.9,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 13,
              wind_kph: 20.9,
              wind_degree: 260,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0.08,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 88,
              feelslike_c: 24.6,
              feelslike_f: 76.3,
              windchill_c: 22.2,
              windchill_f: 71.9,
              heatindex_c: 24.6,
              heatindex_f: 76.3,
              dewpoint_c: 20.4,
              dewpoint_f: 68.7,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18,
              gust_kph: 28.9,
              uv: 5,
            },
            {
              time_epoch: 1721961000,
              time: "2024-07-26 08:00",
              temp_c: 22.4,
              temp_f: 72.3,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 14.5,
              wind_kph: 23.4,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 87,
              cloud: 71,
              feelslike_c: 24.7,
              feelslike_f: 76.5,
              windchill_c: 22.4,
              windchill_f: 72.3,
              heatindex_c: 24.7,
              heatindex_f: 76.5,
              dewpoint_c: 20.1,
              dewpoint_f: 68.2,
              will_it_rain: 1,
              chance_of_rain: 75,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.8,
              gust_kph: 31.8,
              uv: 5,
            },
            {
              time_epoch: 1721964600,
              time: "2024-07-26 09:00",
              temp_c: 23.2,
              temp_f: 73.7,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 15.2,
              wind_kph: 24.5,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.69,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 82,
              cloud: 81,
              feelslike_c: 25.2,
              feelslike_f: 77.4,
              windchill_c: 23.2,
              windchill_f: 73.7,
              heatindex_c: 25.2,
              heatindex_f: 77.4,
              dewpoint_c: 20,
              dewpoint_f: 68,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.6,
              gust_kph: 31.6,
              uv: 5,
            },
            {
              time_epoch: 1721968200,
              time: "2024-07-26 10:00",
              temp_c: 24.2,
              temp_f: 75.6,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 17.2,
              wind_kph: 27.7,
              wind_degree: 258,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 79,
              cloud: 86,
              feelslike_c: 26.2,
              feelslike_f: 79.1,
              windchill_c: 24.2,
              windchill_f: 75.6,
              heatindex_c: 26.2,
              heatindex_f: 79.1,
              dewpoint_c: 20.4,
              dewpoint_f: 68.7,
              will_it_rain: 0,
              chance_of_rain: 63,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.9,
              gust_kph: 32,
              uv: 5,
            },
            {
              time_epoch: 1721971800,
              time: "2024-07-26 11:00",
              temp_c: 24.5,
              temp_f: 76.2,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 17,
              wind_kph: 27.4,
              wind_degree: 258,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.67,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 79,
              cloud: 70,
              feelslike_c: 26.5,
              feelslike_f: 79.7,
              windchill_c: 24.5,
              windchill_f: 76.2,
              heatindex_c: 26.5,
              heatindex_f: 79.7,
              dewpoint_c: 20.8,
              dewpoint_f: 69.4,
              will_it_rain: 1,
              chance_of_rain: 81,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.6,
              gust_kph: 31.6,
              uv: 5,
            },
            {
              time_epoch: 1721975400,
              time: "2024-07-26 12:00",
              temp_c: 24.4,
              temp_f: 75.9,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 14.1,
              wind_kph: 22.7,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.66,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 81,
              cloud: 83,
              feelslike_c: 26.4,
              feelslike_f: 79.5,
              windchill_c: 24.4,
              windchill_f: 75.9,
              heatindex_c: 26.4,
              heatindex_f: 79.5,
              dewpoint_c: 21,
              dewpoint_f: 69.8,
              will_it_rain: 0,
              chance_of_rain: 65,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.8,
              gust_kph: 27,
              uv: 5,
            },
            {
              time_epoch: 1721979000,
              time: "2024-07-26 13:00",
              temp_c: 24.3,
              temp_f: 75.8,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 14.3,
              wind_kph: 23,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.64,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 81,
              cloud: 69,
              feelslike_c: 26.3,
              feelslike_f: 79.4,
              windchill_c: 24.3,
              windchill_f: 75.8,
              heatindex_c: 26.3,
              heatindex_f: 79.4,
              dewpoint_c: 20.9,
              dewpoint_f: 69.6,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.9,
              gust_kph: 28.9,
              uv: 5,
            },
            {
              time_epoch: 1721982600,
              time: "2024-07-26 14:00",
              temp_c: 24.8,
              temp_f: 76.6,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 15.4,
              wind_kph: 24.8,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.62,
              precip_mm: 0.04,
              precip_in: 0,
              snow_cm: 0,
              humidity: 80,
              cloud: 79,
              feelslike_c: 26.8,
              feelslike_f: 80.2,
              windchill_c: 24.8,
              windchill_f: 76.6,
              heatindex_c: 26.8,
              heatindex_f: 80.2,
              dewpoint_c: 21,
              dewpoint_f: 69.8,
              will_it_rain: 1,
              chance_of_rain: 71,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.1,
              gust_kph: 30.8,
              uv: 5,
            },
            {
              time_epoch: 1721986200,
              time: "2024-07-26 15:00",
              temp_c: 24.6,
              temp_f: 76.2,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 15,
              wind_kph: 24.1,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.62,
              precip_mm: 0.15,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 83,
              cloud: 71,
              feelslike_c: 26.7,
              feelslike_f: 80.1,
              windchill_c: 24.6,
              windchill_f: 76.2,
              heatindex_c: 26.7,
              heatindex_f: 80.1,
              dewpoint_c: 21.6,
              dewpoint_f: 70.8,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 17.9,
              gust_kph: 28.8,
              uv: 5,
            },
            {
              time_epoch: 1721989800,
              time: "2024-07-26 16:00",
              temp_c: 24,
              temp_f: 75.1,
              is_day: 1,
              condition: {
                text: "Light rain shower",
                icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
                code: 1240,
              },
              wind_mph: 12.5,
              wind_kph: 20.2,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.61,
              precip_mm: 0.2,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 88,
              cloud: 95,
              feelslike_c: 26.2,
              feelslike_f: 79.1,
              windchill_c: 24,
              windchill_f: 75.1,
              heatindex_c: 26.2,
              heatindex_f: 79.1,
              dewpoint_c: 21.8,
              dewpoint_f: 71.2,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.5,
              gust_kph: 24.9,
              uv: 5,
            },
            {
              time_epoch: 1721993400,
              time: "2024-07-26 17:00",
              temp_c: 23.5,
              temp_f: 74.4,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 12.1,
              wind_kph: 19.4,
              wind_degree: 256,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.62,
              precip_mm: 0.04,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 23.6,
              windchill_f: 74.4,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 21.8,
              dewpoint_f: 71.2,
              will_it_rain: 1,
              chance_of_rain: 78,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.5,
              gust_kph: 25,
              uv: 5,
            },
            {
              time_epoch: 1721997000,
              time: "2024-07-26 18:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.64,
              precip_mm: 0.08,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 25.6,
              feelslike_f: 78.2,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 25.6,
              heatindex_f: 78.2,
              dewpoint_c: 21.7,
              dewpoint_f: 71,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.4,
              gust_kph: 23.1,
              uv: 5,
            },
            {
              time_epoch: 1722000600,
              time: "2024-07-26 19:00",
              temp_c: 23.2,
              temp_f: 73.7,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.67,
              precip_mm: 0.05,
              precip_in: 0,
              snow_cm: 0,
              humidity: 91,
              cloud: 100,
              feelslike_c: 25.4,
              feelslike_f: 77.8,
              windchill_c: 23.2,
              windchill_f: 73.7,
              heatindex_c: 25.4,
              heatindex_f: 77.8,
              dewpoint_c: 21.6,
              dewpoint_f: 70.8,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.6,
              uv: 0,
            },
            {
              time_epoch: 1722004200,
              time: "2024-07-26 20:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.11,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 23,
              windchill_f: 73.3,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 21.7,
              dewpoint_f: 71,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.9,
              gust_kph: 22.4,
              uv: 0,
            },
            {
              time_epoch: 1722007800,
              time: "2024-07-26 21:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 251,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.7,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25.3,
              feelslike_f: 77.6,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25.3,
              heatindex_f: 77.6,
              dewpoint_c: 21.8,
              dewpoint_f: 71.2,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.2,
              gust_kph: 22.8,
              uv: 0,
            },
            {
              time_epoch: 1722011400,
              time: "2024-07-26 22:00",
              temp_c: 23.2,
              temp_f: 73.7,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 11.9,
              wind_kph: 19.1,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.7,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 91,
              cloud: 100,
              feelslike_c: 25.4,
              feelslike_f: 77.8,
              windchill_c: 23.2,
              windchill_f: 73.7,
              heatindex_c: 25.4,
              heatindex_f: 77.8,
              dewpoint_c: 21.7,
              dewpoint_f: 71,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 0,
            },
            {
              time_epoch: 1722015000,
              time: "2024-07-26 23:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.69,
              precip_mm: 0.07,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.3,
              feelslike_f: 77.6,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25.3,
              heatindex_f: 77.6,
              dewpoint_c: 21.6,
              dewpoint_f: 71,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.7,
              gust_kph: 26.9,
              uv: 0,
            },
          ],
        },
        {
          date: "2024-07-27",
          date_epoch: 1722038400,
          day: {
            maxtemp_c: 23.6,
            maxtemp_f: 74.6,
            mintemp_c: 22.6,
            mintemp_f: 72.6,
            avgtemp_c: 23.1,
            avgtemp_f: 73.6,
            maxwind_mph: 14.3,
            maxwind_kph: 23,
            totalprecip_mm: 0.86,
            totalprecip_in: 0.03,
            totalsnow_cm: 0,
            avgvis_km: 9.7,
            avgvis_miles: 6,
            avghumidity: 92,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 89,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: "Patchy rain nearby",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            uv: 6,
          },
          astro: {
            sunrise: "06:10 AM",
            sunset: "07:12 PM",
            moonrise: "11:44 PM",
            moonset: "11:52 AM",
            moon_phase: "Waning Gibbous",
            moon_illumination: 63,
            is_moon_up: 1,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1722018600,
              time: "2024-07-27 00:00",
              temp_c: 22.8,
              temp_f: 73.1,
              is_day: 0,
              condition: {
                text: "Light drizzle",
                icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
                code: 1153,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.67,
              precip_mm: 0.17,
              precip_in: 0.01,
              snow_cm: 0,
              humidity: 94,
              cloud: 100,
              feelslike_c: 25.2,
              feelslike_f: 77.3,
              windchill_c: 22.8,
              windchill_f: 73.1,
              heatindex_c: 25.2,
              heatindex_f: 77.3,
              dewpoint_c: 21.7,
              dewpoint_f: 71.1,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 16.7,
              gust_kph: 26.9,
              uv: 0,
            },
            {
              time_epoch: 1722022200,
              time: "2024-07-27 01:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 14.3,
              wind_kph: 23,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.64,
              precip_mm: 0.05,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 99,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 21.6,
              dewpoint_f: 70.8,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.3,
              gust_kph: 31.1,
              uv: 0,
            },
            {
              time_epoch: 1722025800,
              time: "2024-07-27 02:00",
              temp_c: 22.8,
              temp_f: 73,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 13.4,
              wind_kph: 21.6,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.63,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.1,
              feelslike_f: 77.2,
              windchill_c: 22.8,
              windchill_f: 73,
              heatindex_c: 25.1,
              heatindex_f: 77.2,
              dewpoint_c: 21.5,
              dewpoint_f: 70.7,
              will_it_rain: 1,
              chance_of_rain: 79,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.2,
              gust_kph: 29.3,
              uv: 0,
            },
            {
              time_epoch: 1722029400,
              time: "2024-07-27 03:00",
              temp_c: 22.6,
              temp_f: 72.7,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 12.1,
              wind_kph: 19.4,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1003,
              pressure_in: 29.63,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 22.6,
              windchill_f: 72.7,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 21.5,
              dewpoint_f: 70.8,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.5,
              gust_kph: 26.6,
              uv: 0,
            },
            {
              time_epoch: 1722033000,
              time: "2024-07-27 04:00",
              temp_c: 22.7,
              temp_f: 72.8,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 11.6,
              wind_kph: 18.7,
              wind_degree: 259,
              wind_dir: "W",
              pressure_mb: 1004,
              pressure_in: 29.64,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25.1,
              feelslike_f: 77.1,
              windchill_c: 22.7,
              windchill_f: 72.8,
              heatindex_c: 25.1,
              heatindex_f: 77.1,
              dewpoint_c: 21.5,
              dewpoint_f: 70.7,
              will_it_rain: 0,
              chance_of_rain: 64,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15.9,
              gust_kph: 25.6,
              uv: 0,
            },
            {
              time_epoch: 1722036600,
              time: "2024-07-27 05:00",
              temp_c: 22.6,
              temp_f: 72.7,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 257,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0.04,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25,
              feelslike_f: 77,
              windchill_c: 22.6,
              windchill_f: 72.7,
              heatindex_c: 25,
              heatindex_f: 77,
              dewpoint_c: 21.5,
              dewpoint_f: 70.7,
              will_it_rain: 1,
              chance_of_rain: 71,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.9,
              gust_kph: 23.9,
              uv: 0,
            },
            {
              time_epoch: 1722040200,
              time: "2024-07-27 06:00",
              temp_c: 22.6,
              temp_f: 72.6,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 100,
              feelslike_c: 25,
              feelslike_f: 76.9,
              windchill_c: 22.6,
              windchill_f: 72.6,
              heatindex_c: 25,
              heatindex_f: 76.9,
              dewpoint_c: 21.5,
              dewpoint_f: 70.7,
              will_it_rain: 1,
              chance_of_rain: 77,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 5,
            },
            {
              time_epoch: 1722043800,
              time: "2024-07-27 07:00",
              temp_c: 22.9,
              temp_f: 73.2,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.69,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25.2,
              feelslike_f: 77.4,
              windchill_c: 22.9,
              windchill_f: 73.1,
              heatindex_c: 25.2,
              heatindex_f: 77.4,
              dewpoint_c: 21.7,
              dewpoint_f: 71.1,
              will_it_rain: 1,
              chance_of_rain: 77,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.5,
              gust_kph: 21.7,
              uv: 5,
            },
            {
              time_epoch: 1722047400,
              time: "2024-07-27 08:00",
              temp_c: 23.1,
              temp_f: 73.5,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 256,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.71,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.4,
              feelslike_f: 77.7,
              windchill_c: 23.1,
              windchill_f: 73.5,
              heatindex_c: 25.4,
              heatindex_f: 77.7,
              dewpoint_c: 21.7,
              dewpoint_f: 71.1,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.3,
              gust_kph: 21.4,
              uv: 5,
            },
            {
              time_epoch: 1722051000,
              time: "2024-07-27 09:00",
              temp_c: 23.3,
              temp_f: 73.9,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 255,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.72,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.6,
              feelslike_f: 78,
              windchill_c: 23.3,
              windchill_f: 73.9,
              heatindex_c: 25.6,
              heatindex_f: 78,
              dewpoint_c: 21.8,
              dewpoint_f: 71.3,
              will_it_rain: 0,
              chance_of_rain: 61,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13,
              gust_kph: 21,
              uv: 5,
            },
            {
              time_epoch: 1722054600,
              time: "2024-07-27 10:00",
              temp_c: 23.2,
              temp_f: 73.8,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.72,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.5,
              feelslike_f: 78,
              windchill_c: 23.2,
              windchill_f: 73.8,
              heatindex_c: 25.5,
              heatindex_f: 78,
              dewpoint_c: 21.9,
              dewpoint_f: 71.3,
              will_it_rain: 1,
              chance_of_rain: 73,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.7,
              gust_kph: 20.5,
              uv: 5,
            },
            {
              time_epoch: 1722058200,
              time: "2024-07-27 11:00",
              temp_c: 23.6,
              temp_f: 74.4,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 9.8,
              wind_kph: 15.8,
              wind_degree: 253,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.71,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 25.8,
              feelslike_f: 78.5,
              windchill_c: 23.6,
              windchill_f: 74.4,
              heatindex_c: 25.8,
              heatindex_f: 78.5,
              dewpoint_c: 21.9,
              dewpoint_f: 71.3,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.1,
              gust_kph: 19.5,
              uv: 5,
            },
            {
              time_epoch: 1722061800,
              time: "2024-07-27 12:00",
              temp_c: 23.5,
              temp_f: 74.4,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.69,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 25.8,
              feelslike_f: 78.4,
              windchill_c: 23.6,
              windchill_f: 74.4,
              heatindex_c: 25.8,
              heatindex_f: 78.4,
              dewpoint_c: 21.8,
              dewpoint_f: 71.3,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.2,
              gust_kph: 21.2,
              uv: 5,
            },
            {
              time_epoch: 1722065400,
              time: "2024-07-27 13:00",
              temp_c: 23.6,
              temp_f: 74.6,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.66,
              precip_mm: 0.06,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 25.9,
              feelslike_f: 78.6,
              windchill_c: 23.6,
              windchill_f: 74.6,
              heatindex_c: 25.9,
              heatindex_f: 78.6,
              dewpoint_c: 21.9,
              dewpoint_f: 71.4,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.5,
              gust_kph: 21.7,
              uv: 5,
            },
            {
              time_epoch: 1722069000,
              time: "2024-07-27 14:00",
              temp_c: 23.6,
              temp_f: 74.4,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.66,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 90,
              cloud: 100,
              feelslike_c: 25.8,
              feelslike_f: 78.5,
              windchill_c: 23.6,
              windchill_f: 74.4,
              heatindex_c: 25.8,
              heatindex_f: 78.5,
              dewpoint_c: 21.9,
              dewpoint_f: 71.4,
              will_it_rain: 0,
              chance_of_rain: 60,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 13.4,
              gust_kph: 21.6,
              uv: 5,
            },
            {
              time_epoch: 1722072600,
              time: "2024-07-27 15:00",
              temp_c: 23.5,
              temp_f: 74.2,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 251,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 91,
              cloud: 100,
              feelslike_c: 25.7,
              feelslike_f: 78.3,
              windchill_c: 23.5,
              windchill_f: 74.2,
              heatindex_c: 25.7,
              heatindex_f: 78.3,
              dewpoint_c: 21.9,
              dewpoint_f: 71.4,
              will_it_rain: 1,
              chance_of_rain: 87,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.8,
              uv: 5,
            },
            {
              time_epoch: 1722076200,
              time: "2024-07-27 16:00",
              temp_c: 23.4,
              temp_f: 74.1,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 254,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.65,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.7,
              feelslike_f: 78.2,
              windchill_c: 23.4,
              windchill_f: 74.1,
              heatindex_c: 25.7,
              heatindex_f: 78.2,
              dewpoint_c: 21.9,
              dewpoint_f: 71.4,
              will_it_rain: 1,
              chance_of_rain: 83,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 5,
            },
            {
              time_epoch: 1722079800,
              time: "2024-07-27 17:00",
              temp_c: 23.3,
              temp_f: 74,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 256,
              wind_dir: "WSW",
              pressure_mb: 1004,
              pressure_in: 29.66,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.6,
              feelslike_f: 78.1,
              windchill_c: 23.3,
              windchill_f: 74,
              heatindex_c: 25.6,
              heatindex_f: 78.1,
              dewpoint_c: 21.9,
              dewpoint_f: 71.5,
              will_it_rain: 1,
              chance_of_rain: 85,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.5,
              uv: 5,
            },
            {
              time_epoch: 1722083400,
              time: "2024-07-27 18:00",
              temp_c: 23.2,
              temp_f: 73.7,
              is_day: 1,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                code: 1063,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 254,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.67,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25.5,
              feelslike_f: 77.9,
              windchill_c: 23.2,
              windchill_f: 73.7,
              heatindex_c: 25.5,
              heatindex_f: 77.9,
              dewpoint_c: 21.9,
              dewpoint_f: 71.5,
              will_it_rain: 0,
              chance_of_rain: 60,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.9,
              gust_kph: 19.1,
              uv: 5,
            },
            {
              time_epoch: 1722087000,
              time: "2024-07-27 19:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 8.9,
              wind_kph: 14.4,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25.3,
              feelslike_f: 77.6,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25.3,
              heatindex_f: 77.6,
              dewpoint_c: 21.8,
              dewpoint_f: 71.3,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 11.9,
              gust_kph: 19.2,
              uv: 0,
            },
            {
              time_epoch: 1722090600,
              time: "2024-07-27 20:00",
              temp_c: 22.9,
              temp_f: 73.2,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 249,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 100,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 22.9,
              windchill_f: 73.2,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 21.9,
              dewpoint_f: 71.5,
              will_it_rain: 1,
              chance_of_rain: 82,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.6,
              uv: 0,
            },
            {
              time_epoch: 1722094200,
              time: "2024-07-27 21:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 9.4,
              wind_kph: 15.1,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1006,
              pressure_in: 29.69,
              precip_mm: 0.02,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 100,
              feelslike_c: 25.4,
              feelslike_f: 77.7,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25.4,
              heatindex_f: 77.7,
              dewpoint_c: 22,
              dewpoint_f: 71.6,
              will_it_rain: 0,
              chance_of_rain: 60,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12.8,
              gust_kph: 20.6,
              uv: 0,
            },
            {
              time_epoch: 1722097800,
              time: "2024-07-27 22:00",
              temp_c: 23.1,
              temp_f: 73.6,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 250,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.69,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 100,
              feelslike_c: 25.4,
              feelslike_f: 77.8,
              windchill_c: 23.1,
              windchill_f: 73.6,
              heatindex_c: 25.4,
              heatindex_f: 77.8,
              dewpoint_c: 21.9,
              dewpoint_f: 71.4,
              will_it_rain: 0,
              chance_of_rain: 65,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.3,
              gust_kph: 23,
              uv: 0,
            },
            {
              time_epoch: 1722101400,
              time: "2024-07-27 23:00",
              temp_c: 23,
              temp_f: 73.4,
              is_day: 0,
              condition: {
                text: "Patchy rain nearby",
                icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
                code: 1063,
              },
              wind_mph: 10.7,
              wind_kph: 17.3,
              wind_degree: 252,
              wind_dir: "WSW",
              pressure_mb: 1005,
              pressure_in: 29.68,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 92,
              cloud: 100,
              feelslike_c: 25.3,
              feelslike_f: 77.5,
              windchill_c: 23,
              windchill_f: 73.4,
              heatindex_c: 25.3,
              heatindex_f: 77.5,
              dewpoint_c: 21.6,
              dewpoint_f: 70.9,
              will_it_rain: 1,
              chance_of_rain: 87,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.8,
              gust_kph: 23.8,
              uv: 0,
            },
          ],
        },
      ],
    },
    alerts: {
      alert: [],
    },
  };
  let isDay = response.current.is_day;

  const hours = response.forecast.forecastday[0].hour;

  return (
    <>
      <div className="main-div flex justify-center">
        <div className="main-timeLine-container md:w-[1200px] flex justify-center mt-28 flex-col bg-white rounded-lg">

          {/* UPPER CONTAINER P1 START*/}
          <div className="card-container">
            <div className="div-1 flex flex-row justify-between items-center p-4">
              <p className="text-center font-bold">23/08/2024</p>
              <div className="div-C text-center mt-2">
                <p className="text-4xl font-bold text-black">
                  {response.location.name}
                </p>
                <p className="mt-1 text-lg">{response.location.country}</p>
              </div>
              <img
                className="w-12 h-12"
                src={isDay === 1 ? sun : moon}
                alt="isDayLogo"
              />
            </div>
          </div>
          {/* UPPER CONTAINER P1 END*/}

          <div className="divider">WEATHER TIMELINE</div>

          {/* UPPER CONTAINER P2 START*/}
          <div
            className={`second-container flex ${
              hours.length > 11 ? "overflow-x-auto" : ""
            }`}
          >
            {hours.map((element, index) => {
              return (
                <TimeLineCard
                  key={index}
                  icon={element.condition.icon}
                  time={element.time}
                />
              );
            })}
          </div>
          {/* UPPER CONTAINER P2 END*/}

          {/* INPUT SECTION FOR NUMBER OF FORECAST DAYS START */}
        </div>
      </div>
    </>
  );
}

export default Forecast;
